global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "engine"
    static_configs:
      - targets: ["engine:8060"] 
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]      
