// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/api/grpc/points.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Баланс - запрос
type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // ID пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_internal_api_grpc_points_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_points_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_points_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// Баланс - ответ
type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        float64                `protobuf:"fixed64,1,opt,name=points,proto3" json:"points,omitempty"` // кол-во баллов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_internal_api_grpc_points_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_points_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_points_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceResponse) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

// Транзакции - запрос
type TnxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`         // ID пользователя
	Datefrom      string                 `protobuf:"bytes,2,opt,name=datefrom,proto3" json:"datefrom,omitempty"` // дата с
	Dateto        string                 `protobuf:"bytes,3,opt,name=dateto,proto3" json:"dateto,omitempty"`     // дата по
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TnxRequest) Reset() {
	*x = TnxRequest{}
	mi := &file_internal_api_grpc_points_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TnxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TnxRequest) ProtoMessage() {}

func (x *TnxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_points_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TnxRequest.ProtoReflect.Descriptor instead.
func (*TnxRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_points_proto_rawDescGZIP(), []int{2}
}

func (x *TnxRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *TnxRequest) GetDatefrom() string {
	if x != nil {
		return x.Datefrom
	}
	return ""
}

func (x *TnxRequest) GetDateto() string {
	if x != nil {
		return x.Dateto
	}
	return ""
}

// Транзакции - ответ
type TnxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tnx           []*TnxMessage          `protobuf:"bytes,1,rep,name=Tnx,proto3" json:"Tnx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TnxResponse) Reset() {
	*x = TnxResponse{}
	mi := &file_internal_api_grpc_points_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TnxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TnxResponse) ProtoMessage() {}

func (x *TnxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_points_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TnxResponse.ProtoReflect.Descriptor instead.
func (*TnxResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_points_proto_rawDescGZIP(), []int{3}
}

func (x *TnxResponse) GetTnx() []*TnxMessage {
	if x != nil {
		return x.Tnx
	}
	return nil
}

type TnxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`             // UUID транзакции
	Points        float64                `protobuf:"fixed64,2,opt,name=points,proto3" json:"points,omitempty"`       // кол-во баллов
	CommitDate    string                 `protobuf:"bytes,3,opt,name=CommitDate,proto3" json:"CommitDate,omitempty"` // дата/время транзакции / дата в будущем, в которую начислить баллы
	Commit        bool                   `protobuf:"varint,4,opt,name=Commit,proto3" json:"Commit,omitempty"`        // транзакция обработана
	TypeTnx       int32                  `protobuf:"varint,5,opt,name=TypeTnx,proto3" json:"TypeTnx,omitempty"`      // тип операции
	Order         string                 `protobuf:"bytes,6,opt,name=order,proto3" json:"order,omitempty"`           // ID заказа
	Transfer      string                 `protobuf:"bytes,7,opt,name=transfer,proto3" json:"transfer,omitempty"`     // ID операции перевода баллов
	Redeem        string                 `protobuf:"bytes,8,opt,name=redeem,proto3" json:"redeem,omitempty"`         // ID операции списания баллов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TnxMessage) Reset() {
	*x = TnxMessage{}
	mi := &file_internal_api_grpc_points_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TnxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TnxMessage) ProtoMessage() {}

func (x *TnxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_grpc_points_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TnxMessage.ProtoReflect.Descriptor instead.
func (*TnxMessage) Descriptor() ([]byte, []int) {
	return file_internal_api_grpc_points_proto_rawDescGZIP(), []int{4}
}

func (x *TnxMessage) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *TnxMessage) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *TnxMessage) GetCommitDate() string {
	if x != nil {
		return x.CommitDate
	}
	return ""
}

func (x *TnxMessage) GetCommit() bool {
	if x != nil {
		return x.Commit
	}
	return false
}

func (x *TnxMessage) GetTypeTnx() int32 {
	if x != nil {
		return x.TypeTnx
	}
	return 0
}

func (x *TnxMessage) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *TnxMessage) GetTransfer() string {
	if x != nil {
		return x.Transfer
	}
	return ""
}

func (x *TnxMessage) GetRedeem() string {
	if x != nil {
		return x.Redeem
	}
	return ""
}

var File_internal_api_grpc_points_proto protoreflect.FileDescriptor

const file_internal_api_grpc_points_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/api/grpc/points.proto\x12\x06points\"$\n" +
	"\x0eBalanceRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\")\n" +
	"\x0fBalanceResponse\x12\x16\n" +
	"\x06points\x18\x01 \x01(\x01R\x06points\"T\n" +
	"\n" +
	"TnxRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bdatefrom\x18\x02 \x01(\tR\bdatefrom\x12\x16\n" +
	"\x06dateto\x18\x03 \x01(\tR\x06dateto\"3\n" +
	"\vTnxResponse\x12$\n" +
	"\x03Tnx\x18\x01 \x03(\v2\x12.points.TnxMessageR\x03Tnx\"\xd4\x01\n" +
	"\n" +
	"TnxMessage\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x01R\x06points\x12\x1e\n" +
	"\n" +
	"CommitDate\x18\x03 \x01(\tR\n" +
	"CommitDate\x12\x16\n" +
	"\x06Commit\x18\x04 \x01(\bR\x06Commit\x12\x18\n" +
	"\aTypeTnx\x18\x05 \x01(\x05R\aTypeTnx\x12\x14\n" +
	"\x05order\x18\x06 \x01(\tR\x05order\x12\x1a\n" +
	"\btransfer\x18\a \x01(\tR\btransfer\x12\x16\n" +
	"\x06redeem\x18\b \x01(\tR\x06redeem2\x81\x01\n" +
	"\tGetPoints\x12?\n" +
	"\n" +
	"GetBalance\x12\x16.points.BalanceRequest\x1a\x17.points.BalanceResponse\"\x00\x123\n" +
	"\x06GetTnx\x12\x12.points.TnxRequest\x1a\x13.points.TnxResponse\"\x00B9Z7github.com/glkeru/loyalty/points/internal/api/grpc;grpcb\x06proto3"

var (
	file_internal_api_grpc_points_proto_rawDescOnce sync.Once
	file_internal_api_grpc_points_proto_rawDescData []byte
)

func file_internal_api_grpc_points_proto_rawDescGZIP() []byte {
	file_internal_api_grpc_points_proto_rawDescOnce.Do(func() {
		file_internal_api_grpc_points_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_grpc_points_proto_rawDesc), len(file_internal_api_grpc_points_proto_rawDesc)))
	})
	return file_internal_api_grpc_points_proto_rawDescData
}

var file_internal_api_grpc_points_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_api_grpc_points_proto_goTypes = []any{
	(*BalanceRequest)(nil),  // 0: points.BalanceRequest
	(*BalanceResponse)(nil), // 1: points.BalanceResponse
	(*TnxRequest)(nil),      // 2: points.TnxRequest
	(*TnxResponse)(nil),     // 3: points.TnxResponse
	(*TnxMessage)(nil),      // 4: points.TnxMessage
}
var file_internal_api_grpc_points_proto_depIdxs = []int32{
	4, // 0: points.TnxResponse.Tnx:type_name -> points.TnxMessage
	0, // 1: points.GetPoints.GetBalance:input_type -> points.BalanceRequest
	2, // 2: points.GetPoints.GetTnx:input_type -> points.TnxRequest
	1, // 3: points.GetPoints.GetBalance:output_type -> points.BalanceResponse
	3, // 4: points.GetPoints.GetTnx:output_type -> points.TnxResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_grpc_points_proto_init() }
func file_internal_api_grpc_points_proto_init() {
	if File_internal_api_grpc_points_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_grpc_points_proto_rawDesc), len(file_internal_api_grpc_points_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_grpc_points_proto_goTypes,
		DependencyIndexes: file_internal_api_grpc_points_proto_depIdxs,
		MessageInfos:      file_internal_api_grpc_points_proto_msgTypes,
	}.Build()
	File_internal_api_grpc_points_proto = out.File
	file_internal_api_grpc_points_proto_goTypes = nil
	file_internal_api_grpc_points_proto_depIdxs = nil
}
